# Generated by Django 4.2.1 on 2023-05-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('imie', models.CharField(max_length=25)),
                ('drugie_imie', models.CharField(blank=True, max_length=25, null=True)),
                ('nazwisko', models.CharField(max_length=50)),
                ('haslo', models.CharField(max_length=100)),
                ('pesel', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('data_urodzenia', models.DateField()),
                ('plec', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], max_length=1)),
                ('ulica', models.CharField(max_length=50)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('miasto', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('utworzony', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
