# Generated by Django 4.2.1 on 2023-05-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='pesel',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
